package com.syc.dashboard.framework.common.exceptions

object ErrorCodes {
    // ADMIN
    const val ADMIN_ALREADY_REGISTERED_WITH_EMAIL = "1_001"
    const val ADMIN_NOT_FOUND = "1_002"
    const val ADMIN_FIND_BY_ID_FAILED = "1_003"
    const val ADMIN_NOT_EXIST_WITH_EMAIL = "1_004"
    const val ADMIN_STATE_CHANGE_NOT_ALLOWED_FOR_INACTIVE_STATUS = "1_005"
    const val ADMIN_NOT_FOUND_WITH_EMAIL = "1_006"
    const val ALL_USERS_FIND_BY_FILTER_FAILED = "1_007"

    // EMPLOYEE
    const val EMPLOYEE_ALREADY_REGISTERED_WITH_EMAIL = "2_001"
    const val EMPLOYEE_FIND_BY_EMAIL_FAILED = "2_002"
    const val EMPLOYEE_NOT_FOUND = "2_003"
    const val EMPLOYEE_FIND_BY_ID_FAILED = "2_004"
    const val EMPLOYEE_STATE_CHANGE_NOT_ALLOWED = "2_005"
    const val EMPLOYEE_NOT_FOUND_WITH_EMAIL = "2_006"
    const val EMPLOYEE_FIND_BY_FILTER_FAILED = "2_007"
    const val EMPLOYEE_PASSWORD_MISMATCH = "2_008"
    const val EMPLOYEE_FIND_BY_STATUS_FAILED = "2_009"
    const val EMPLOYEE_FIND_BY_ID_AND_STATUS_FAILED = "2_010"
    const val MANAGER_AND_ADMIN_NOT_FOUND = "2_011"
    const val EMPLOYEE_COUNT_FIND_BY_STATUS_FAILED = "2_012"
    const val EMPLOYEE_ROLE_INVALID = "2_013"
    const val EMPLOYEE_SUPERVISOR_LIST_FIND_BY_FILTER_FAILED = "2_014"
    const val EMPLOYEE_SUPERVISOR_FIND_BY_ID_FAILED = "2_015"
    const val EMPLOYEE_VACATIONS_FIND_BY_ID_FAILED = "2_016"

    // TIMESHEET
    const val TIMESHEET_FIND_BY_ID_FAILED = "3_001"
    const val TIMESHEET_STATE_CHANGE_NOT_ALLOWED_FOR_INACTIVE_STATUS = "3_002"
    const val TIMESHEET_FIND_BY_STATUS_FAILED = "3_003"
    const val TIMESHEET_FIND_SUBMITTED_FOR_APPROVAL_FOR_ADMIN_FAILED = "3_004"
    const val TIMESHEET_SEARCH_BY_ADMIN_FAILED = "3_005"
    const val TIMESHEET_SEARCH_BY_MANAGER_FAILED = "3_006"
    const val TIMESHEET_FIND_SUBMITTED_FOR_APPROVAL_FOR_MANAGER_FAILED = "3_007"
    const val TIMESHEET_FIND_SUBMITTED_FOR_APPROVAL_FOR_EMPLOYEE_FAILED = "3_008"
    const val TIMESHEET_ROW_FIND_BY_ID_FAILED = "3_009"
    const val TIMESHEET_COUNT_FIND_BY_EMPLOYEE_ID_AND_STATUS_FAILED = "3_010"
    const val TIMESHEET_COUNT_FIND_BY_MANAGER_ID_AND_STATUS_FAILED = "3_011"
    const val TIMESHEET_COUNT_FIND_BY_ADMIN_BY_STATUS_FAILED = "3_012"
    const val TIMESHEET_ROW_EXPORT_TO_EXCEL_BY_ID_FAILED = "3_013"
    const val TIMESHEET_LIST_SEARCH_BY_EMPLOYEE_FAILED = "3_014"
    const val TIMESHEET_COUNT_FIND_BY_SUPERVISOR_ID_AND_STATUS_FAILED = "3_015"
    const val TIMESHEET_ROWS_SEARCH_FAILED = "3_016"
    const val TIMESHEET_ROW_FIND_BY_ID_EXPORT_QUICKBOOK_FAILED = "3_017"
    const val TIMESHEET_WEEK_ENDING_DATE_ALREADY_EXISTS = "3_018"

    // JOBCODE
    const val JOBCODE_ALREADY_REGISTERED_WITH_ID = "4_001"
    const val JOBCODE_NOT_FOUND = "4_002"
    const val JOBCODE_FIND_BY_ID_FAILED = "4_003"
    const val JOBCODE_FIND_BY_CODE_FAILED = "4_004"
    const val JOBCODE_STATE_CHANGE_NOT_ALLOWED = "4_005"
    const val JOBCODE_FIND_BY_FILTER_FAILED = "4_006"
    const val JOBCODE_AND_COSTCODE_FIND_FAILED = "4_007"
    const val JOBCODE_WITH_COSTCODE_NOT_FOUND = "4_008"
    const val COSTCODE_FIND_BY_ID_FAILED = "4_009"
    const val COSTCODE_FIND_FAILED = "4_010"
    const val COSTCODE_NOT_FOUND = "4_011"
    const val COSTCODE_FIND_BY_JOB_CODE_ID_AND_ID_FAILED = "4_012"
    const val JOBCODE_AND_COSTCODE_FIND_BY_CODE_FAILED = "4_013"
    const val COSTCODE_ALREADY_REGISTERED_WITH_CODE = "4_014"
    const val COSTCODE_FIND_BY_FILTER_FAILED = "4_015"
    const val JOBCODE_FIND_BY_WATCHER_FAILED = "4_016"

    // SETTINGS
    const val SETTINGS_NOT_FOUND = "5_001"
    const val SETTINGS_STATE_CHANGE_NOT_ALLOWED = "5_002"
    const val SETTINGS_FIND_BY_ID_FAILED = "5_003"
    const val SETTINGS_WITH_TENANT_ID_ALREADY_EXIST = "5_004"
    const val EXPENSE_TYPE_FIND_BY_TENANT_ID_FAILED = "5_005"
    const val MILEAGE_RATE_FIND_BY_TENANT_ID_FAILED = "5_006"
    const val PAYROLL_ITEM_FIND_BY_TENANT_ID_FAILED = "5_007"
    const val PAYROLL_ITEM_FIND_BY_ID_FAILED = "5_008"
    const val YEARLY_QUARTER_FIND_BY_TENANT_ID_FAILED = "5_009"
    const val VEHICLE_INFO_FIND_BY_ID_FAILED = "5_010"
    const val VEHICLE_INFO_FIND_BY_FILTER_FAILED = "5_011"
    const val VEHICLE_INFO_FIND_FAILED = "5_012"

    // NOTIFICATION IN_APP
    const val NOTIFICATION_IN_APP_NOT_FOUND = "6_001"
    const val NOTIFICATION_IN_APP_FIND_BY_ID_FAILED = "6_002"
    const val NOTIFICATION_COUNT_FIND_BY_IN_APP_BY_STATUS_FAILED = "6_003"

    // NOTIFICATION EMAIL
    const val NOTIFICATION_EMAIL_NOT_FOUND = "7_001"
    const val NOTIFICATION_COUNT_FIND_BY_EMAIL_BY_STATUS_FAILED = "7_002"

    // NOTIFICATION MOBILE
    const val NOTIFICATION_MOBILE_NOT_FOUND = "8_001"
    const val NOTIFICATION_COUNT_FIND_BY_MOBILE_BY_STATUS_FAILED = "8_002"

    // EXPENSES REPORT
    const val EXPENSE_REPORT_STATE_CHANGE_NOT_ALLOWED_FOR_INACTIVE_STATUS = "9_001"
    const val EXPENSE_REPORT_NOT_EXIST = "9_002"
    const val EXPENSE_REPORT_FIND_BY_ID_FAILED = "9_003"
    const val EXPENSE_REPORT_FIND_FAILED = "9_004"
    const val EXPENSE_REPORT_COUNT_FIND_BY_ADMIN_BY_STATUS_FAILED = "9_005"
    const val EXPENSE_REPORT_COUNT_FIND_BY_EMPLOYEE_BY_STATUS_FAILED = "9_006"
    const val EXPENSE_REPORT_COUNT_FIND_BY_SUPERVISOR_BY_STATUS_FAILED = "9_007"
    const val EXPENSE_REPORT_FOR_SUYASH_BY_ID_FAILED = "9_008"
    const val EXPENSE_REPORT_FOR_EMPLOYEE_BY_ID_FAILED = "9_009"
    const val EXPENSE_REPORT_ALREADY_ADDED_FOR_SPECIFIED_PERIOD = "9_010"
    const val EXPENSE_REPORT_EXPORT_TO_EXCEL_BY_ID_FAILED = "9_011"
    const val EXPENSE_REPORT_EXPORT_TO_PDF_BY_ID_FAILED = "9_012"
    const val EXPENSE_REPORT_SEARCH_BY_ADMIN_FAILED = "9_013"
    const val EXPENSE_REPORT_ROW_EXPORT_TO_EXCEL_BY_ID_FAILED = "9_014"
    const val EXPENSE_REPORT_ROW_SEARCH_BY_JOBCODE_AND_PERIOD_FROM_FAILED = "9_015"
    const val EXPENSE_REPORT_ROW_EXPORT_TO_PDF_BY_ID_FAILED = "9_016"
    const val JOBCODE_FIND_BY_PERIODFORM_FAILED = "9_017"
    const val EXPENSE_REPORT_COUNT_FIND_BY_MANAGER_BY_STATUS_FAILED = "9_018"
    const val EXPENSE_REPORT_FIND_BY_TENANT_ID_FAILED = "9_019"

    // Date
    const val INVALID_DATE_FORMAT = "10_001"

    // DOCUMENT
    const val DOCUMENT_STATE_CHANGE_NOT_ALLOWED_FOR_INACTIVE_STATUS = "11_001"
    const val DOCUMENT_UPLOAD_FAILED = "11_002"
    const val INVALID_DOCUMENT_ENTITY = "11_003"
    const val DOCUMENT_VIEW_BY_ID_FAILED = "11_004"
    const val DOCUMENT_NOT_FOUND = "11_004"
    const val DOCUMENT_FIND_BY_ID_FAILED = "11_005"

    // Project
    const val PROJECT_ALREADY_REGISTERED_WITH_ID = "12_001"
    const val PROJECT_FIND_BY_ID_FAILED = "12_002"
    const val PROJECT_STATE_CHANGE_NOT_ALLOWED = "12_003"
    const val PROJECT_NOT_FOUND = "12_004"
    const val PROJECT_FIND_BY_FILTER_FAILED = "12_005"
    const val PROJECT_FIND_BY_ACTIVE_FILTER_FAILED = "12_006"
    const val PROJECT_DOES_NOT_EXIST = "12_007"

    // Project Report
    const val PROJECT_REPORT_NOT_FOUND = "13_001"
    const val PROJECT_REPORT_FIND_BY_ID_FAILED = "13_002"
    const val PROJECT_REPORT_FIND_FAILED = "13_003"
    const val PROJECT_REPORT_STATE_CHANGE_NOT_ALLOWED = "13_004"

    // System Config
    const val SYSTEM_CONFIG_FIND_FAILED = "14_001"
    const val SYSTEM_CONFIG_UI_FIND_FAILED = "14_002"

    // Tvhg Input
    const val TVHG_INPUT_FIND_BY_ID_FAILED = "15_001"
    const val TVHG_INPUT_STATE_CHANGE_NOT_ALLOWED = "15_002"
    const val TVHG_INPUT_EVENT_STREAM_NOT_EXIST_IN_EVENT_STORE = "15_003"
    const val TVHG_INPUT_NOT_FOUND = "15_004"
    const val TVHG_INPUT_STRUCTURE_DRAWING_DATA_FIND_BY_ID_FAILED = "15_005"
    const val TVHG_INPUT_PROJECT_INFORMATION_FIND_BY_ID_FAILED = "15_006"
    const val TVHG_INPUT_HYDROLOGIC_INFORMATION_FIND_BY_ID_FAILED = "15_007"
    const val TVHG_INPUT_PIPE_DRAWING_INFORMATION_FIND_BY_ID_FAILED = "15_008"

    // tvhg config
    const val TVHG_CONFIG_UNITS_FIND_BY_ID_FAILED = "16_001"
    const val TVHG_CONFIG_STATE_CHANGE_NOT_ALLOWED = "16_002"
    const val TVHG_CONFIG_EVENT_STREAM_NOT_EXIST_IN_EVENT_STORE = "16_003"
    const val TVHG_CONFIG_FIND_FAILED = "16_004"
    const val TVHG_CONFIG_DESIGN_STORM_FIND_BY_ID_FAILED = "16_005"
    const val TVHG_CONFIG_MD_STANDARD_NUMBER_FIND_BY_ID_FAILED = "16_006"

    // vehicle log
    const val VEHICLE_LOG_EVENT_STREAM_NOT_EXIST_IN_EVENT_STORE = "17_001"
    const val VEHICLE_LOG_FIND_BY_TENANT_ID_FAILED = "17_002"
    const val VEHICLE_LOG_FIND_BY_FILTER_FAILED = "17_003"
    const val VEHICLE_LOG_FIND_BY_VEHICLE_ID_FAILED = "17_004"
    const val VEHICLE_LOG_FIND_BY_ID_FAILED = "17_005"
    const val VEHICLE_LOG_FOR_EMPLOYEE_ID_FAILED = "17_006"
}
