<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
<p>Hi ${recipientName},</p>
<p>The cost code has been <b>${status}</b>. Please find the details below:</p>
<p><b>Job Code:</b> ${jobCode}</p>
<p><b>Cost Code:</b> ${costCode}</p>
<p><b>CostCode Description:</b> ${description}</p>
<p><b>Registered By:</b> ${createdBy}</p>
<p>Suyash Portal log in - ${portalLink}</p>
<p><i>Please do not reply, this email box is not monitored.</i></p>
</body>
</html>
